# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7a3abdbd55a836ad89ab24cb559a24e02e6d68755f3ac61b985e38ce34dead52da9a934340869c0caf03b09dd1879309498512c563d11296d94dee75b44e407

test:
  secret_key_base: 84cecf427859e365df705b4c18878fc0b8d0cba96045de27112591f3f197c425ac3d18e8cb9e102a0f1adb108ef5205a304529ef90a2c186933d2727f35579d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
